/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidacaoRouteImport } from './routes/validacao'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as InscritosRouteImport } from './routes/inscritos'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as CursoRouteImport } from './routes/curso'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIndicadoresRouteImport } from './routes/api/indicadores'
import { Route as ApiHotmartRouteImport } from './routes/api/hotmart'
import { Route as ApiCompraArquivoRouteImport } from './routes/api/compra/arquivo'

const ValidacaoRoute = ValidacaoRouteImport.update({
  id: '/validacao',
  path: '/validacao',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const InscritosRoute = InscritosRouteImport.update({
  id: '/inscritos',
  path: '/inscritos',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const CursoRoute = CursoRouteImport.update({
  id: '/curso',
  path: '/curso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndicadoresRoute = ApiIndicadoresRouteImport.update({
  id: '/api/indicadores',
  path: '/api/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotmartRoute = ApiHotmartRouteImport.update({
  id: '/api/hotmart',
  path: '/api/hotmart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompraArquivoRoute = ApiCompraArquivoRouteImport.update({
  id: '/api/compra/arquivo',
  path: '/api/compra/arquivo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/curso': typeof CursoRoute
  '/inscricao': typeof InscricaoRoute
  '/inscritos': typeof InscritosRoute
  '/oferta': typeof OfertaRoute
  '/validacao': typeof ValidacaoRoute
  '/api/hotmart': typeof ApiHotmartRoute
  '/api/indicadores': typeof ApiIndicadoresRoute
  '/api/compra/arquivo': typeof ApiCompraArquivoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/curso': typeof CursoRoute
  '/inscricao': typeof InscricaoRoute
  '/inscritos': typeof InscritosRoute
  '/oferta': typeof OfertaRoute
  '/validacao': typeof ValidacaoRoute
  '/api/hotmart': typeof ApiHotmartRoute
  '/api/indicadores': typeof ApiIndicadoresRoute
  '/api/compra/arquivo': typeof ApiCompraArquivoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/curso': typeof CursoRoute
  '/inscricao': typeof InscricaoRoute
  '/inscritos': typeof InscritosRoute
  '/oferta': typeof OfertaRoute
  '/validacao': typeof ValidacaoRoute
  '/api/hotmart': typeof ApiHotmartRoute
  '/api/indicadores': typeof ApiIndicadoresRoute
  '/api/compra/arquivo': typeof ApiCompraArquivoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/curso'
    | '/inscricao'
    | '/inscritos'
    | '/oferta'
    | '/validacao'
    | '/api/hotmart'
    | '/api/indicadores'
    | '/api/compra/arquivo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/curso'
    | '/inscricao'
    | '/inscritos'
    | '/oferta'
    | '/validacao'
    | '/api/hotmart'
    | '/api/indicadores'
    | '/api/compra/arquivo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/curso'
    | '/inscricao'
    | '/inscritos'
    | '/oferta'
    | '/validacao'
    | '/api/hotmart'
    | '/api/indicadores'
    | '/api/compra/arquivo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CursoRoute: typeof CursoRoute
  InscricaoRoute: typeof InscricaoRoute
  InscritosRoute: typeof InscritosRoute
  OfertaRoute: typeof OfertaRoute
  ValidacaoRoute: typeof ValidacaoRoute
  ApiHotmartRoute: typeof ApiHotmartRoute
  ApiIndicadoresRoute: typeof ApiIndicadoresRoute
  ApiCompraArquivoRoute: typeof ApiCompraArquivoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validacao': {
      id: '/validacao'
      path: '/validacao'
      fullPath: '/validacao'
      preLoaderRoute: typeof ValidacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscritos': {
      id: '/inscritos'
      path: '/inscritos'
      fullPath: '/inscritos'
      preLoaderRoute: typeof InscritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curso': {
      id: '/curso'
      path: '/curso'
      fullPath: '/curso'
      preLoaderRoute: typeof CursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/indicadores': {
      id: '/api/indicadores'
      path: '/api/indicadores'
      fullPath: '/api/indicadores'
      preLoaderRoute: typeof ApiIndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotmart': {
      id: '/api/hotmart'
      path: '/api/hotmart'
      fullPath: '/api/hotmart'
      preLoaderRoute: typeof ApiHotmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compra/arquivo': {
      id: '/api/compra/arquivo'
      path: '/api/compra/arquivo'
      fullPath: '/api/compra/arquivo'
      preLoaderRoute: typeof ApiCompraArquivoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CursoRoute: CursoRoute,
  InscricaoRoute: InscricaoRoute,
  InscritosRoute: InscritosRoute,
  OfertaRoute: OfertaRoute,
  ValidacaoRoute: ValidacaoRoute,
  ApiHotmartRoute: ApiHotmartRoute,
  ApiIndicadoresRoute: ApiIndicadoresRoute,
  ApiCompraArquivoRoute: ApiCompraArquivoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
